### PR TITLE
Updated Loss Function

### PR DESCRIPTION
**Pull request by StatMixedML**
I made the following changes:
- added hierarchical temporal loss in `models.loss`
  - replaced the loop in the cosine-loss with vectorized calculation 
  - added the temporal hierarchical loss from TS2Vec
- added hierarchical temporal loss argument in model function call in `simts`
- Updated torch version in requirements

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by xingyu617** [comment]
Thanks for the improvement!

**Comment by xingyu617** [comment]
Thanks for the improvement!

**Comment by StatMixedML** [comment]
It is a great approach and I would love to contribute more to the repo. Let me know in case of open topics. You can assign them to me.

**Comment by xcvil** [comment]
Hi! Thanks a lot for your contribution! I hope this project can be helpful in real-world applications! > It is a great approach and I would love to contribute more to the repo. Let me know in case of open topics. You can assign them to me.

**Pull request merged**
